[package]
name = "opfspack-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"
crc32fast = "1.3.2"
aes-gcm = "0.10.3"
getrandom = { version = "0.2", features = ["js"] }
lz4_flex = { version = "0.11", default-features = false, features = ["safe-encode", "safe-decode"] }

[profile.release]
opt-level = "z"
lto = true

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
